-- Intentionally empty: Sodium seeds no data.
--
-- Sign-in is GitHub-only (see README → "GitHub sign-in"), so there are no
-- demo accounts. Auth automatically creates each user's private workspace;
-- repositories are connected through the GitHub App.
--
-- Test suites provision their own throwaway data:
--   - the database security tests create tenants inside rolled-back
--     transactions (integration and browser tests)
--   - the dashboard browser tests create ephemeral users via the auth admin
--     API and delete them afterwards (apps/web/e2e/global-setup.ts)
