-- Intentionally empty: Sodium seeds no data.
--
-- Sign-in is GitHub-only (see README → "GitHub sign-in"), so there are no
-- demo accounts. Everything else is created through the product itself:
-- create an organization in onboarding, then "Use the local fixture
-- repository" to get an analyzable repo without GitHub credentials.
--
-- Test suites provision their own throwaway data:
--   - the database security tests create tenants inside rolled-back
--     transactions (apps/worker/test/db-rls.test.ts)
--   - the dashboard browser tests create ephemeral users via the auth admin
--     API and delete them afterwards (apps/web/e2e/global-setup.ts)
