import type { ActionContract } from "@sodium/contracts";
import { detectAppDir } from "@sodium/analyzer";
import { posix } from "node:path";

/**
 * The integration PR installs the hosted loader and, only when approved tools
 * bind to server actions, a small reviewed first-party binding component.
 */

export interface PrGenInput {
  siteId: string;
  loaderOrigin: string;
  contracts: ActionContract[];
  /** Existing repo-relative app shell that owns the document head. */
  targetPath: string;
  targetSource: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface PrGenOutput {
  files: GeneratedFile[];
  title: string;
  body: string;
  branch: string;
  /** No PR is necessary when the exact loader tag is already present. */
  alreadyInstalled: boolean;
}

export const INSTALL_TARGETS = [
  "app/layout.tsx",
  "src/app/layout.tsx",
  "app/layout.jsx",
  "src/app/layout.jsx",
  "pages/_document.tsx",
  "src/pages/_document.tsx",
  "pages/_document.jsx",
  "src/pages/_document.jsx",
  "app/root.tsx",
  "app/root.jsx",
  "src/app.html",
  "index.html",
  "src/index.html",
  "public/index.html",
  "src/layouts/Layout.astro",
  "src/layouts/BaseLayout.astro",
] as const;

/** Selects the same App Router project as analysis, including monorepos. */
export function findInstallTarget(files: string[]): string | null {
  const fileSet = new Set(files);
  const appDir = detectAppDir(files);
  const appTargets = appDir
    ? [`${appDir}/layout.tsx`, `${appDir}/layout.jsx`]
    : [];
  return (
    [...appTargets, ...INSTALL_TARGETS].find((candidate) =>
      fileSet.has(candidate),
    ) ?? null
  );
}

export function generateIntegration(input: PrGenInput): PrGenOutput {
  const bridgeContracts = input.contracts.filter(
    (contract) => contract.handler.kind === "bridge",
  );
  if (bridgeContracts.length > 0) {
    return generateBridgeIntegration(input, bridgeContracts);
  }
  const snippet = loaderSnippet(input.loaderOrigin, input.siteId);
  const edited = installLoaderScript(input.targetSource, snippet);
  if (!edited) {
    throw new Error(
      `Could not find a safe <head> or <body> insertion point in ${input.targetPath}. Add the loader snippet manually.`,
    );
  }

  const alreadyInstalled = edited === input.targetSource;
  const files = alreadyInstalled
    ? []
    : [{ path: input.targetPath, content: edited }];
  const body = [
    "## Sodium WebMCP loader",
    "",
    `Installs Sodium for site \`${input.siteId}\`.`,
    "",
    "### Change",
    `- Adds one loader \`<script>\` to \`${input.targetPath}\``,
    `- Exposes ${input.contracts.length} approved tool${input.contracts.length === 1 ? "" : "s"} from the signed remote manifest`,
    "- Does not add generated application code or change existing behavior",
    "",
    "The loader only activates on origins allowed in Sodium and always uses the latest published tool settings.",
    "",
    "Generated by Sodium",
  ].join("\n");

  return {
    files,
    title: "Install Sodium WebMCP loader",
    body,
    branch: `sodium/install-${input.siteId.replace(/^site_/, "")}`,
    alreadyInstalled,
  };
}

function generateBridgeIntegration(
  input: PrGenInput,
  bridgeContracts: ActionContract[],
): PrGenOutput {
  if (!/(^|\/)app\/layout\.(tsx|jsx)$/.test(input.targetPath)) {
    throw new Error(
      "Server-action tools require a Next.js App Router root layout so the reviewed first-party bindings can be installed safely.",
    );
  }
  const componentPath = input.targetPath.replace(
    /app\/layout\.(tsx|jsx)$/,
    "sodium/SodiumAgent.tsx",
  );
  const component = generateAgentComponent(
    input,
    bridgeContracts,
    componentPath,
  );
  const edited = installAgentComponent(
    input.targetSource,
    input.targetPath,
    componentPath,
  );
  if (!edited) {
    throw new Error(
      `Could not safely render SodiumAgent inside ${input.targetPath}. Add the generated component manually and rerun the integration.`,
    );
  }
  const files: GeneratedFile[] = [{ path: componentPath, content: component }];
  if (edited !== input.targetSource) {
    files.push({ path: input.targetPath, content: edited });
  }
  const stateChanging = bridgeContracts.filter(
    (contract) => contract.riskLevel !== "read_only",
  );
  return {
    files,
    title: "Install Sodium WebMCP tools",
    body: [
      "## Sodium WebMCP integration",
      "",
      `Installs the hosted loader and ${bridgeContracts.length} reviewed first-party server-action binding${bridgeContracts.length === 1 ? "" : "s"}.`,
      "",
      "### Change",
      `- Adds \`${componentPath}\` with bindings to existing exported server actions`,
      `- Renders \`<SodiumAgent />\` from \`${input.targetPath}\``,
      `- Exposes ${input.contracts.length} enabled tool${input.contracts.length === 1 ? "" : "s"} from the signed remote manifest`,
      `- Keeps ${stateChanging.length} state-affecting tool${stateChanging.length === 1 ? "" : "s"} behind the app's existing validation and authorization`,
      "",
      "Review and merge this PR before publishing bridge-backed tools. The hosted loader alone cannot call private server functions.",
      "",
      "Generated by Sodium",
    ].join("\n"),
    branch: `sodium/install-${input.siteId.replace(/^site_/, "")}`,
    alreadyInstalled: false,
  };
}

function generateAgentComponent(
  input: PrGenInput,
  contracts: ActionContract[],
  componentPath: string,
): string {
  const imports: string[] = [];
  const handlers: string[] = [];
  for (const [index, contract] of contracts.entries()) {
    if (contract.handler.kind !== "bridge") continue;
    const source = contract.evidence.find(
      (evidence) =>
        evidence.kind === "source" && evidence.primitive === "server_action",
    );
    if (!source || source.kind !== "source") {
      throw new Error(
        `Tool ${contract.name} has no server-action source binding; run analysis again before generating the integration.`,
      );
    }
    const exportName = exportedActionName(source.excerpt);
    if (!exportName) {
      throw new Error(
        `Tool ${contract.name} cites ${source.filePath}, but its exported action name could not be recovered safely.`,
      );
    }
    const alias = `sodiumAction${index}`;
    const actionPath = source.filePath.replace(/\.(tsx?|jsx?|mjs)$/, "");
    const relativeImport = posix.relative(
      posix.dirname(componentPath),
      actionPath,
    );
    const importPath = relativeImport.startsWith(".")
      ? relativeImport
      : "./" + relativeImport;
    imports.push(
      `import { ${exportName} as ${alias} } from ${JSON.stringify(importPath)};`,
    );
    handlers.push(
      `  ${JSON.stringify(contract.handler.bridgeKey)}: async (input) => ${actionInvocation(alias, exportName, source.excerpt)},`,
    );
  }

  return `/** @generated by Sodium — regenerate from the dashboard. */
"use client";

import { useEffect } from "react";
${imports.join("\n")}

type BridgeHandler = (input: Record<string, unknown>) => unknown | Promise<unknown>;
type SodiumWindow = Window & {
  __sodiumBridge?: { handlers: Map<string, BridgeHandler> };
};

const handlers: Record<string, BridgeHandler> = {
${handlers.join("\n")}
};

export function SodiumAgent() {
  useEffect(() => {
    const sodiumWindow = window as SodiumWindow;
    const registry = (sodiumWindow.__sodiumBridge ??= { handlers: new Map() });
    for (const [key, handler] of Object.entries(handlers)) registry.handlers.set(key, handler);
    window.dispatchEvent(new Event("sodium:bridge-change"));

    if (!document.querySelector("script[data-sodium-loader]")) {
      const script = document.createElement("script");
      script.src = ${JSON.stringify(input.loaderOrigin.replace(/\/+$/, "") + "/agent/v1.js")};
      script.async = true;
      script.dataset.site = ${JSON.stringify(input.siteId)};
      script.dataset.sodiumLoader = "true";
      document.head.appendChild(script);
    }

    return () => {
      for (const key of Object.keys(handlers)) registry.handlers.delete(key);
      window.dispatchEvent(new Event("sodium:bridge-change"));
    };
  }, []);
  return null;
}
`;
}

function exportedActionName(excerpt: string): string | null {
  return (
    /export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/.exec(excerpt)?.[1] ??
    /export\s+const\s+([A-Za-z_$][\w$]*)\s*=/.exec(excerpt)?.[1] ??
    null
  );
}

function actionInvocation(
  alias: string,
  exportName: string,
  excerpt: string,
): string {
  const params = actionParameters(excerpt, exportName);
  if (params.length === 0) return `${alias}()`;
  if (params.length === 1 && /\bFormData\b/.test(params[0]!.typeText)) {
    return `(() => { const formData = new FormData(); for (const [key, value] of Object.entries(input)) { if (value !== undefined && value !== null) formData.append(key, String(value)); } return ${alias}(formData); })()`;
  }
  if (params.length === 1 && looksLikeObjectParameter(params[0]!.typeText)) {
    return `${alias}(input as never)`;
  }
  return `${alias}(${params
    .map((parameter) => `input[${JSON.stringify(parameter.name)}] as never`)
    .join(", ")})`;
}

function actionParameters(
  excerpt: string,
  exportName: string,
): { name: string; typeText: string }[] {
  const nameIndex = excerpt.indexOf(exportName);
  const open = excerpt.indexOf("(", nameIndex + exportName.length);
  if (nameIndex < 0 || open < 0) return [];
  let depth = 0;
  let close = -1;
  for (let index = open; index < excerpt.length; index++) {
    const char = excerpt[index];
    if (char === "(") depth++;
    if (char === ")" && --depth === 0) {
      close = index;
      break;
    }
  }
  if (close < 0) return [];
  return splitTopLevel(excerpt.slice(open + 1, close)).flatMap((parameter) => {
    const match =
      /^\s*([A-Za-z_$][\w$]*)\s*(?:\?|=)?\s*(?::\s*([\s\S]+))?$/.exec(
        parameter.trim(),
      );
    return match ? [{ name: match[1]!, typeText: match[2]?.trim() ?? "" }] : [];
  });
}

function splitTopLevel(source: string): string[] {
  const parts: string[] = [];
  let start = 0;
  let depth = 0;
  for (let index = 0; index < source.length; index++) {
    const char = source[index]!;
    if ("{[(<".includes(char)) depth++;
    else if ("}])>".includes(char)) depth--;
    else if (char === "," && depth === 0) {
      parts.push(source.slice(start, index));
      start = index + 1;
    }
  }
  const tail = source.slice(start).trim();
  if (tail) parts.push(tail);
  return parts;
}

function looksLikeObjectParameter(typeText: string): boolean {
  const normalized = typeText.trim();
  if (!normalized) return true;
  return (
    normalized.startsWith("{") ||
    /^[A-Z][A-Za-z0-9_$]*(?:<.*>)?$/.test(normalized) ||
    /Record\s*</.test(normalized)
  );
}

function installAgentComponent(
  source: string,
  targetPath: string,
  componentPath: string,
): string | null {
  const withoutLoader = source.replace(
    /\s*<script\b(?=[^>]*\bdata-site\s*=)(?=[^>]*\/agent\/v1\.js)[^>]*>\s*<\/script>/gi,
    "",
  );
  const importPath = posix.relative(
    posix.dirname(targetPath),
    componentPath.replace(/\.(tsx|jsx)$/, ""),
  );
  const normalizedImport = importPath.startsWith(".")
    ? importPath
    : "./" + importPath;
  const importLine = `import { SodiumAgent } from ${JSON.stringify(normalizedImport)};`;
  let edited = withoutLoader;
  const importPattern = new RegExp(
    `from\\s+["']${escapeRegex(normalizedImport)}["']`,
  );
  if (!importPattern.test(edited)) {
    const directive = /^(?:\s*["']use [^"']+["'];?\s*)+/.exec(edited);
    const insertAt = directive?.[0].length ?? 0;
    edited = `${edited.slice(0, insertAt)}${insertAt > 0 ? "\n" : ""}${importLine}\n${edited.slice(insertAt)}`;
  }
  if (edited.includes("<SodiumAgent")) return edited;
  const body = /<body\b[^>]*>/.exec(edited);
  if (!body) return null;
  const insertAt = body.index + body[0].length;
  return `${edited.slice(0, insertAt)}\n        <SodiumAgent />${edited.slice(insertAt)}`;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Exact copyable tag shown in the dashboard and inserted by the PR. */
export function loaderSnippet(loaderOrigin: string, siteId: string): string {
  const origin = loaderOrigin.replace(/\/+$/, "");
  return `<script src="${escapeAttribute(origin)}/agent/v1.js" data-site="${escapeAttribute(siteId)}"></script>`;
}

/**
 * Idempotently installs or repairs the loader tag. Existing Sodium tags are
 * replaced in place, preventing duplicate loaders after URL or site changes.
 */
export function installLoaderScript(
  source: string,
  snippet: string,
): string | null {
  const scriptPattern =
    /<script\b(?=[^>]*\bdata-site\s*=\s*["'][^"']+["'])(?=[^>]*\bsrc\s*=\s*["'][^"']*\/agent\/v1\.js[^"']*["'])[^>]*>\s*<\/script>/gi;
  const matches = [...source.matchAll(scriptPattern)];
  if (matches.length > 0) {
    const first = matches[0]!;
    const start = first.index!;
    const end = start + first[0].length;
    const before = source.slice(0, start);
    const after = source.slice(end).replace(scriptPattern, "");
    return before + snippet + after;
  }

  const closingHead = source.search(/<\/head\s*>/i);
  if (closingHead >= 0) {
    return insertIndented(source, closingHead, snippet);
  }

  const bodyOpen = /<body\b[^>]*>/i.exec(source);
  if (bodyOpen) {
    const insertAt = bodyOpen.index + bodyOpen[0].length;
    const lineStart = source.lastIndexOf("\n", bodyOpen.index - 1) + 1;
    const indent =
      source.slice(lineStart, bodyOpen.index).match(/^\s*/)?.[0] ?? "";
    const rest = source.slice(insertAt);
    const beforeExistingContent = rest.startsWith("\n") ? "" : `\n${indent}`;
    return `${source.slice(0, insertAt)}\n${indent}  ${snippet}${beforeExistingContent}${rest}`;
  }

  const closingBody = source.search(/<\/body\s*>/i);
  if (closingBody >= 0) {
    return insertIndented(source, closingBody, snippet);
  }

  return null;
}

function insertIndented(
  source: string,
  index: number,
  snippet: string,
): string {
  const lineStart = source.lastIndexOf("\n", index - 1) + 1;
  const indent = source.slice(lineStart, index).match(/^\s*/)?.[0] ?? "";
  return `${source.slice(0, index)}${indent}  ${snippet}
${source.slice(index)}`;
}

function escapeAttribute(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}
