import type { ActionContract } from "@sodium/contracts";

/**
 * Generates the integration PR file set for a repository with approved
 * bridge-handler contracts. Constraints:
 *  - minimal, clearly `@generated`-marked files under `sodium/`
 *  - reuses the app's existing server actions (validation/auth stay there)
 *  - a two-line, string-level layout edit; when the layout doesn't match the
 *    safe pattern, the change ships as instructions instead of a blind edit
 *  - never targets the default branch (enforced by the repo provider)
 */

export interface PrGenInput {
  siteId: string;
  /** Loader origin, e.g. https://sodium.example — script src becomes {origin}/agent/v1.js */
  loaderOrigin: string;
  contracts: ActionContract[];
  /** repo-relative path of the root layout, e.g. "app/layout.tsx". */
  layoutPath: string | null;
  layoutSource: string | null;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface PrGenOutput {
  files: GeneratedFile[];
  title: string;
  body: string;
  branch: string;
  /** True when the layout could not be edited automatically. */
  layoutNeedsManualEdit: boolean;
}

const GENERATED_HEADER = `/**
 * @generated by sodium — DO NOT EDIT BY HAND.
 * Regenerate from the sodium dashboard (Publish → Regenerate integration).
 * Changes here are overwritten by the next regeneration PR.
 */`;

export function generateIntegration(input: PrGenInput): PrGenOutput {
  const bridgeContracts = input.contracts.filter(
    (contract) => contract.handler.kind === "bridge",
  );
  const files: GeneratedFile[] = [];

  files.push({
    path: "sodium/bridge.ts",
    content: generateBridgeModule(bridgeContracts),
  });
  files.push({
    path: "sodium/SodiumAgent.tsx",
    content: generateAgentComponent(input),
  });
  files.push({
    path: "sodium/manifest-meta.json",
    content: generateManifestMeta(input),
  });
  files.push({
    path: "sodium/verify.mjs",
    content: generateVerifyScript(bridgeContracts),
  });
  files.push({ path: "sodium/README.md", content: generateReadme(input) });

  let layoutNeedsManualEdit = true;
  if (input.layoutPath && input.layoutSource) {
    const edited = editLayout(input.layoutSource);
    if (edited) {
      files.push({ path: input.layoutPath, content: edited });
      layoutNeedsManualEdit = false;
    }
  }

  const stateChanging = input.contracts.filter(
    (contract) => contract.riskLevel !== "read_only",
  );
  const body = [
    "## Sodium WebMCP integration",
    "",
    `Installs the pinned agent loader for site \`${input.siteId}\` and binds ${bridgeContracts.length} approved action${bridgeContracts.length === 1 ? "" : "s"} to your existing application functions.`,
    "",
    "### What this PR adds",
    "- `sodium/SodiumAgent.tsx` — renders the versioned loader `<script>` and registers bridge handlers",
    "- `sodium/bridge.ts` — binds approved tool contracts to your existing server actions (your validation and authorization run unchanged)",
    "- `sodium/manifest-meta.json` — the approved contracts this integration was generated from",
    "- `sodium/verify.mjs` — checks the bridge still exports a handler per approved contract (`node sodium/verify.mjs`)",
    layoutNeedsManualEdit
      ? '\n### Manual step required\nYour root layout could not be edited automatically. Add to it:\n```tsx\nimport { SodiumAgent } from "../sodium/SodiumAgent";\n// inside <body>:\n<SodiumAgent />\n```'
      : `- \`${input.layoutPath}\` — two-line edit rendering \`<SodiumAgent />\``,
    "",
    "### Review notes",
    `- ${stateChanging.length} tool${stateChanging.length === 1 ? " is" : "s are"} state-affecting; each calls an existing server action and inherits its auth, validation, idempotency and confirmation behavior.`,
    "- Nothing executes until the site's manifest is published from the sodium dashboard; the loader fails closed without a validly signed manifest for this exact origin.",
    "- All generated files are marked `@generated`; regenerate them from the dashboard instead of editing.",
    "",
    "🤖 Generated by sodium",
  ].join("\n");

  return {
    files,
    title: `Add sodium WebMCP agent integration (${input.contracts.length} approved tools)`,
    body,
    branch: `sodium/integration-${input.siteId.replace(/^site_/, "")}`,
    layoutNeedsManualEdit,
  };
}

function bridgeImportInfo(
  contract: ActionContract,
): { importName: string; importPath: string } | null {
  if (contract.handler.kind !== "bridge") return null;
  const source = contract.evidence.find(
    (evidence) =>
      evidence.kind === "source" && evidence.primitive === "server_action",
  );
  if (!source || source.kind !== "source") return null;
  const importName = camel(
    contract.handler.bridgeKey.replace(/^actions\./, ""),
  );
  const importPath = "../" + source.filePath.replace(/\.(ts|tsx|js|jsx)$/, "");
  return { importName, importPath };
}

export function generateBridgeModule(contracts: ActionContract[]): string {
  const imports: string[] = [];
  const entries: string[] = [];
  for (const contract of contracts) {
    if (contract.handler.kind !== "bridge") continue;
    const info = bridgeImportInfo(contract);
    if (!info) {
      entries.push(
        `  // TODO(review): no source binding found for ${contract.handler.bridgeKey}; wire it to the right function.\n  // "${contract.handler.bridgeKey}": async (input) => { throw new Error("not wired"); },`,
      );
      continue;
    }
    imports.push(`import { ${info.importName} } from "${info.importPath}";`);
    const confirmGuard =
      contract.confirmation === "required"
        ? `\n    // This action is ${contract.riskLevel.replace("_", "-")}: the browser agent is told confirmation is
    // required, and your function below must keep enforcing it server-side.`
        : "";
    entries.push(
      `  "${contract.handler.bridgeKey}": async (input) => {${confirmGuard}
    return await ${info.importName}(input as Parameters<typeof ${info.importName}>[0]);
  },`,
    );
  }

  return `${GENERATED_HEADER}
"use client";

import { registerBridgeHandlers, type BridgeHandler } from "@sodium/runtime/bridge";
${imports.join("\n")}

/**
 * Approved action bridge: each key was reviewed and published in the sodium
 * dashboard. Handlers call your existing server actions — authentication,
 * authorization, input validation and idempotency all run in your code.
 */
export const handlers: Record<string, BridgeHandler> = {
${entries.join("\n")}
};

export function registerSodiumBridge(): () => void {
  return registerBridgeHandlers(handlers);
}
`;
}

function generateAgentComponent(input: PrGenInput): string {
  return `${GENERATED_HEADER}
"use client";

import { useEffect } from "react";
import { registerSodiumBridge } from "./bridge";

const LOADER_SRC = "${input.loaderOrigin}/agent/v1.js";
const SITE_ID = "${input.siteId}";

/** Renders the pinned sodium loader and registers first-party bridge handlers. */
export function SodiumAgent() {
  useEffect(() => {
    const unregister = registerSodiumBridge();
    if (!document.querySelector('script[data-sodium-loader]')) {
      const script = document.createElement("script");
      script.src = LOADER_SRC;
      script.async = true;
      script.dataset.site = SITE_ID;
      script.dataset.sodiumLoader = "true";
      document.head.appendChild(script);
    }
    return unregister;
  }, []);
  return null;
}
`;
}

function generateManifestMeta(input: PrGenInput): string {
  return (
    JSON.stringify(
      {
        $comment:
          "@generated by sodium — approved contracts backing this integration",
        siteId: input.siteId,
        generatedAt: new Date().toISOString(),
        tools: input.contracts.map((contract) => ({
          actionId: contract.actionId,
          name: contract.name,
          title: contract.title,
          riskLevel: contract.riskLevel,
          confirmation: contract.confirmation,
          handler: contract.handler,
        })),
      },
      null,
      2,
    ) + "\n"
  );
}

function generateVerifyScript(contracts: ActionContract[]): string {
  const keys = contracts
    .map((contract) =>
      contract.handler.kind === "bridge" ? contract.handler.bridgeKey : null,
    )
    .filter((key): key is string => key !== null);
  return `${GENERATED_HEADER.replace("/**", "/*")}
// Static verification: every approved bridge key must appear in sodium/bridge.ts.
// Runs with plain Node (no app code is executed): node sodium/verify.mjs
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const expected = ${JSON.stringify(keys, null, 2)};
const source = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "bridge.ts"), "utf8");
const missing = expected.filter((key) => !source.includes(JSON.stringify(key)));
if (missing.length > 0) {
  console.error("missing bridge handlers:", missing.join(", "));
  process.exit(1);
}
console.log(\`ok: \${expected.length} bridge handlers present\`);
`;
}

function generateReadme(input: PrGenInput): string {
  return `# sodium integration (generated)

These files are **@generated** by [sodium](${input.loaderOrigin}) for site \`${input.siteId}\`.

- Do not edit by hand; regenerate from the dashboard (Publish → Regenerate integration).
- \`bridge.ts\` binds approved WebMCP tools to your existing server actions.
- The loader only registers tools from the signed manifest published for this
  exact origin, and only while the application is open in a WebMCP-capable
  browser agent.
- Verify integrity in CI with \`node sodium/verify.mjs\`.
`;
}

/**
 * Two-line layout edit: add the import and render <SodiumAgent /> right after
 * the opening <body …> tag. Returns null when the file doesn't match the safe
 * pattern (PR then carries manual instructions instead).
 */
export function editLayout(source: string): string | null {
  if (source.includes("SodiumAgent")) return source; // already integrated
  const bodyMatch = /<body[^>]*>/.exec(source);
  if (!bodyMatch) return null;
  const insertAt = bodyMatch.index + bodyMatch[0].length;
  const withComponent = `${source.slice(0, insertAt)}\n        <SodiumAgent />${source.slice(insertAt)}`;
  return `import { SodiumAgent } from "../sodium/SodiumAgent";\n${withComponent}`;
}

function camel(text: string): string {
  return text.replace(/_([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}
