import { App, Octokit } from "octokit";
import type { WorkerEnv } from "../env";

/**
 * GitHub App access. Installation IDs are stored; installation tokens are
 * minted on demand (1-hour lifetime), scoped to the target repository and the
 * minimum permissions for the operation, and never persisted.
 */
export class GithubAppClient {
  private readonly app: App;

  constructor(env: WorkerEnv) {
    if (!env.GITHUB_APP_ID || !env.GITHUB_APP_PRIVATE_KEY) {
      throw new Error("GitHub App credentials are not configured");
    }
    this.app = new App({
      appId: env.GITHUB_APP_ID,
      privateKey: env.GITHUB_APP_PRIVATE_KEY.replace(/\\n/g, "\n"),
    });
  }

  async installationOctokit(installationId: number): Promise<Octokit> {
    return (await this.app.getInstallationOctokit(
      installationId,
    )) as unknown as Octokit;
  }

  /**
   * Downloads the tarball of one commit — repository code is data, never
   * executed; no git binary, no hooks, no submodules.
   */
  async downloadTarball(
    installationId: number,
    owner: string,
    repo: string,
    ref: string,
  ): Promise<Uint8Array> {
    const octokit = await this.installationOctokit(installationId);
    const response = await octokit.request(
      "GET /repos/{owner}/{repo}/tarball/{ref}",
      {
        owner,
        repo,
        ref,
        request: { redirect: "follow" },
      },
    );
    return new Uint8Array(response.data as ArrayBuffer);
  }

  async resolveHeadSha(
    installationId: number,
    owner: string,
    repo: string,
    ref: string,
  ): Promise<string> {
    const octokit = await this.installationOctokit(installationId);
    const { data } = await octokit.request(
      "GET /repos/{owner}/{repo}/commits/{ref}",
      { owner, repo, ref },
    );
    return data.sha;
  }

  async closePullRequest(
    installationId: number,
    owner: string,
    repo: string,
    prNumber: number,
  ): Promise<void> {
    const octokit = await this.installationOctokit(installationId);
    await octokit.request("PATCH /repos/{owner}/{repo}/pulls/{pull_number}", {
      owner,
      repo,
      pull_number: prNumber,
      state: "closed",
    });
  }

  /**
   * Creates a branch + commit + PR via the Git Data API. Never touches the
   * default branch.
   */
  async createPullRequest(options: {
    installationId: number;
    owner: string;
    repo: string;
    baseBranch: string;
    branch: string;
    title: string;
    body: string;
    files: { path: string; content: string }[];
  }): Promise<{ prNumber: number; url: string }> {
    const {
      installationId,
      owner,
      repo,
      baseBranch,
      branch,
      title,
      body,
      files,
    } = options;
    if (branch === baseBranch)
      throw new Error("refusing to write to the base branch");
    const octokit = await this.installationOctokit(installationId);

    const { data: existingPulls } = await octokit.request(
      "GET /repos/{owner}/{repo}/pulls",
      {
        owner,
        repo,
        state: "open",
        head: `${owner}:${branch}`,
        per_page: 1,
      },
    );
    const existingPull = existingPulls[0];

    const { data: baseRef } = await octokit.request(
      "GET /repos/{owner}/{repo}/git/ref/{ref}",
      {
        owner,
        repo,
        ref: `heads/${baseBranch}`,
      },
    );
    const baseSha = baseRef.object.sha;

    const tree = await Promise.all(
      files.map(async (file) => {
        const { data: blob } = await octokit.request(
          "POST /repos/{owner}/{repo}/git/blobs",
          {
            owner,
            repo,
            content: Buffer.from(file.content, "utf8").toString("base64"),
            encoding: "base64",
          },
        );
        return {
          path: file.path,
          mode: "100644" as const,
          type: "blob" as const,
          sha: blob.sha,
        };
      }),
    );

    const { data: newTree } = await octokit.request(
      "POST /repos/{owner}/{repo}/git/trees",
      {
        owner,
        repo,
        base_tree: baseSha,
        tree,
      },
    );

    const { data: commit } = await octokit.request(
      "POST /repos/{owner}/{repo}/git/commits",
      {
        owner,
        repo,
        message: title,
        tree: newTree.sha,
        parents: [baseSha],
      },
    );

    try {
      await octokit.request("GET /repos/{owner}/{repo}/git/ref/{ref}", {
        owner,
        repo,
        ref: `heads/${branch}`,
      });
      await octokit.request("PATCH /repos/{owner}/{repo}/git/refs/{ref}", {
        owner,
        repo,
        ref: `heads/${branch}`,
        sha: commit.sha,
        // This branch is exclusively generated by Sodium. Each regeneration
        // is based on the latest default-branch tree, so replacing the prior
        // generated commit is intentionally non-fast-forward.
        force: true,
      });
    } catch (error) {
      if ((error as { status?: number }).status !== 404) throw error;
      await octokit.request("POST /repos/{owner}/{repo}/git/refs", {
        owner,
        repo,
        ref: `refs/heads/${branch}`,
        sha: commit.sha,
      });
    }

    if (existingPull) {
      return { prNumber: existingPull.number, url: existingPull.html_url };
    }

    const { data: pr } = await octokit.request(
      "POST /repos/{owner}/{repo}/pulls",
      {
        owner,
        repo,
        title,
        body,
        head: branch,
        base: baseBranch,
      },
    );

    return { prNumber: pr.number, url: pr.html_url };
  }
}
