/**
 * @generated by sodium — DO NOT EDIT BY HAND.
 * Regenerate from the sodium dashboard (Publish → Regenerate integration).
 * Changes here are overwritten by the next regeneration PR.
 */
"use client";

import {
  registerBridgeHandlers,
  type BridgeHandler,
} from "@sodium/runtime/bridge";
import { addToCart } from "../app/actions";
import { cancelOrder } from "../app/actions";

/**
 * Approved action bridge: each key was reviewed and published in the sodium
 * dashboard. Handlers call your existing server actions — authentication,
 * authorization, input validation and idempotency all run in your code.
 */
export const handlers: Record<string, BridgeHandler> = {
  "actions.add_to_cart": async (input) => {
    return await addToCart(input as Parameters<typeof addToCart>[0]);
  },
  "actions.cancel_order": async (input) => {
    // This action is destructive: the browser agent is told confirmation is
    // required, and the function below keeps enforcing it server-side.
    return await cancelOrder(input as Parameters<typeof cancelOrder>[0]);
  },
};

export function registerSodiumBridge(): () => void {
  return registerBridgeHandlers(handlers);
}
