/**
 * @generated by sodium — the approved, published tool set for this fixture.
 * Mirrors what the platform's manifest endpoint serves after the review +
 * publish flow (see apps/web); kept in-repo so the fixture is self-contained.
 */
import { annotationsForRisk, type PublishedTool } from "@sodium/contracts";

export const FIXTURE_SITE_ID = "site_fixtureshop01";

export const fixtureTools: PublishedTool[] = [
  {
    name: "read_products",
    title: "Read product catalog",
    description:
      "Reads the product names, prices and stock levels visible on the products page.",
    inputSchema: {
      type: "object",
      properties: {},
      required: [],
      additionalProperties: false,
    },
    annotations: annotationsForRisk("read_only"),
    riskLevel: "read_only",
    confirmation: "none",
    routes: [{ pathPattern: "/products" }],
    handler: {
      kind: "extract",
      fields: [
        {
          name: "names",
          selector: "[data-product-name]",
          attribute: "data-product-name",
          all: true,
        },
        {
          name: "prices",
          selector: "[data-product-price]",
          attribute: "data-product-price",
          all: true,
        },
        {
          name: "stock",
          selector: "[data-product-stock]",
          attribute: "data-product-stock",
          all: true,
        },
        {
          name: "cart_size",
          selector: "[data-cart-size]",
          attribute: "data-cart-size",
        },
      ],
    },
  },
  {
    name: "open_product",
    title: "Open a product page",
    description: "Navigates to the detail page for a specific product id.",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          description: "Product id, e.g. widget",
          minLength: 1,
          maxLength: 64,
        },
      },
      required: ["id"],
      additionalProperties: false,
    },
    annotations: annotationsForRisk("read_only"),
    riskLevel: "read_only",
    confirmation: "none",
    routes: [{ pathPattern: "/**" }],
    handler: { kind: "navigate", urlTemplate: "/products/{id}" },
  },
  {
    name: "submit_contact",
    title: "Submit the contact form",
    description:
      "Fills in and submits the contact form with name, email, topic and message. [changes application state; confirm with the user before use]",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", minLength: 2, maxLength: 80 },
        email: { type: "string", format: "email" },
        topic: {
          type: "string",
          enum: ["support", "sales", "feedback"],
          default: "support",
        },
        message: { type: "string", minLength: 10, maxLength: 2000 },
      },
      required: ["name", "email", "message"],
      additionalProperties: false,
    },
    annotations: annotationsForRisk("state_changing"),
    riskLevel: "state_changing",
    confirmation: "recommended",
    routes: [{ pathPattern: "/contact" }],
    handler: {
      kind: "form",
      formSelector: "#contact-form",
      fieldMap: {
        name: "name",
        email: "email",
        topic: "topic",
        message: "message",
      },
    },
  },
  {
    name: "add_to_cart",
    title: "Add a product to the cart",
    description:
      "Adds a quantity of a product to the shopping cart through the shop's own action. Easily reversed.",
    inputSchema: {
      type: "object",
      properties: {
        productId: { type: "string", minLength: 1, maxLength: 64 },
        quantity: { type: "integer", minimum: 1, maximum: 10 },
      },
      required: ["productId", "quantity"],
      additionalProperties: false,
    },
    annotations: annotationsForRisk("reversible"),
    riskLevel: "reversible",
    confirmation: "none",
    routes: [{ pathPattern: "/**" }],
    handler: { kind: "bridge", bridgeKey: "actions.add_to_cart" },
  },
  {
    name: "cancel_order",
    title: "Cancel an order",
    description:
      "Cancels a pending order through the shop's own action. [DESTRUCTIVE action; requires explicit user confirmation before use]",
    inputSchema: {
      type: "object",
      properties: {
        orderId: { type: "string", minLength: 1, maxLength: 64 },
        confirm: {
          type: "boolean",
          description: "Must be true after the user explicitly confirmed",
        },
      },
      required: ["orderId", "confirm"],
      additionalProperties: false,
    },
    annotations: annotationsForRisk("destructive"),
    riskLevel: "destructive",
    confirmation: "required",
    routes: [{ pathPattern: "/orders", requiresSelector: "[data-signed-in]" }],
    handler: { kind: "bridge", bridgeKey: "actions.cancel_order" },
  },
];
