/**
 * @generated by sodium — DO NOT EDIT BY HAND.
 * Fixture variant: the loader and manifest are served by THIS app
 * (`/agent.js`, `/fixture-manifest`) so the fixture is self-contained; a real
 * integration points at the sodium platform origin instead.
 */
"use client";

import { useEffect } from "react";
import { registerSodiumBridge } from "./bridge";

const SITE_ID = "site_fixtureshop01";

/** Renders the pinned sodium loader and registers first-party bridge handlers. */
export function SodiumAgent() {
  useEffect(() => {
    const unregister = registerSodiumBridge();
    if (!document.querySelector("script[data-sodium-loader]")) {
      const script = document.createElement("script");
      script.src = "/agent.js";
      script.async = true;
      script.dataset.site = SITE_ID;
      script.dataset.manifest = new URL(
        window.location.search.includes("manifestQuery=")
          ? `/fixture-manifest?${new URLSearchParams(window.location.search).get("manifestQuery")}`
          : "/fixture-manifest",
        window.location.origin,
      ).toString();
      script.dataset.telemetry = "off";
      script.dataset.sodiumLoader = "true";
      document.head.appendChild(script);
    }
    return unregister;
  }, []);
  return null;
}
