/*
 * @generated by sodium — DO NOT EDIT BY HAND.
 * Static verification: every approved bridge key must appear in sodium/bridge.ts.
 * Runs with plain Node (no app code is executed): node sodium/verify.mjs
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const expected = ["actions.add_to_cart", "actions.cancel_order"];
const source = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "bridge.ts"), "utf8");
const missing = expected.filter((key) => !source.includes(JSON.stringify(key)));
if (missing.length > 0) {
  console.error("missing bridge handlers:", missing.join(", "));
  process.exit(1);
}
console.log(`ok: ${expected.length} bridge handlers present`);
